version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: golf
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "33061:3306"
    volumes:
      - /databases/mysql:/var/lib/mysql
