<?php

namespace Database\Factories;

use DragonCode\Support\Facades\Helpers\Arr;
use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\Course;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Course>
 */
class CourseFactory extends Factory
{

    protected $model = Course::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {

        return [
            'name' => $this->faker->randomElement($this->courses()),
            'address' => $this->faker->randomElement($this->addresses()),
            'image' => $this->faker->randomElement($this->images()),
        ];
    }

    public function courses() {
        return [
            'Pinehurst Golf Club',
            'Augusta National Golf Club',
            'St. Andrews Links',
            'Pebble Beach Golf Links',
            'Royal Melbourne Golf Club',
            'Cypress Point Club',
            'Muirfield Golf Links',
            'Merion Golf Club',
            'Bandon Dunes Golf Resort',
            'Valderrama Golf Club',
            'Torrey Pines Golf Course',
            'Royal County Down Golf Club',
            'Bethpage Black Course',
            'Whistling Straits',
            'Carnoustie Golf Links',
            'Kiawah Island Golf Resort',
            'Royal Portrush Golf Club',
            'Turnberry Golf Resort',
            'Shinnecock Hills Golf Club',
            'Baltusrol Golf Club',
            'Pine Valley Golf Club',
            'Winged Foot Golf Club',
            'Oakmont Country Club',
            'Erin Hills',
            'Royal Birkdale Golf Club',
            'The Old Course at Half Moon Bay',
            'Congressional Country Club',
            'Sunningdale Golf Club',
            'The Ocean Course at Kiawah Island',
            'Ballybunion Golf Club',
            'Oak Hill Country Club',
            'Whistler Golf Club',
            'Royal Troon Golf Club',
            'Seminole Golf Club',
            'The Links at Spanish Bay',
            'Gleneagles Hotel and Golf Courses',
            'Pine Needles Lodge & Golf Club',
            'Firestone Country Club',
            'Streamsong Resort',
            'The Ocean Course at Hammock Beach',
            'The Quarry at La Quinta',
            'Quail Hollow Club',
            'Trump Turnberry Resort',
            'Olympic Club',
            'The Links at Crowbush Cove',
            'Kingsbarns Golf Links',
            'Bandon Trails',
            'TPC Sawgrass',
            'Westchester Country Club',
            'Royal Dornoch Golf Club',
            'Whispering Pines Golf Club',
            'Serenity Valley Links',
            'Rolling Hills Retreat Golf Course',
            'Enchanted Meadows Golf Resort',
            'Crimson Ridge Golf Club',
            'Tranquil Haven Greens',
            'Mystic Dunes Golf Retreat',
            'Silver Creek Fairways',
            'Sunflower Valley Golf Course',
            'Wildwood Pines Golf Club',
            'Emerald Isle Golf Links',
            'Sandstone Bluffs Golf Resort',
            'Moonlight Bay Golf Club',
            'Thunderbird Ridge Golf Course',
            'Oasis Mirage Greens',
            'Sapphire Springs Golf Retreat',
            'Willowbrook Meadows Golf Club',
            'Sunburst Ridge Golf Resort',
            'Hidden Cove Golf Links',
            'Whispering Willow Greens',
            'Crystal Falls Golf Retreat',
            'Timberline Trails Golf Club',
            'Starlight Meadows Golf Resort',
            'Solstice Sun Greens',
            'Redwood Ridge Golf Course',
            'Oasis Oasis Golf Retreat',
            'Azul Vista Golf Club',
            'Sunset Shores Golf Links',
            'Serendipity Sands Golf Resort',
            'Crimson Valley Golf Club',
            'Tranquil Gardens Greens',
            'Enchanted Pines Golf Course',
            'Reflection Lake Golf Retreat',
            'Silverstone Bluffs Golf Club',
            'Sunlit Canyon Greens',
            'Whispering Winds Golf Resort',
            'Moonlight Valley Golf Retreat',
            'Thunderbolt Ridge Golf Club',
            'Oasis Serenity Greens',
            'Cobalt Cove Golf Links',
            'Crystal Sky Golf Resort',
            'Willowmere Meadows Golf Retreat',
            'Sunhaven Greens',
            'Riverbend Golf Club',
            'Serenity Pines Golf Resort',
            'Scarlet Hills Golf Retreat',
            'Timberwolf Golf Club',
            'Starshine Greens',
            'Solstice Valley Golf Resort',
            'Ruby Falls Golf Course'
        ];
    }

    public function images() {

        $host = env('APP_URL', 'http://localhost');

        return [
            "$host/media/courses/golf-course-1.jpg",
            "$host/media/courses/golf-course-2.jpg",
            "$host/media/courses/golf-course-3.jpg",
            "$host/media/courses/golf-course-4.jpg",
            "$host/media/courses/golf-course-5.jpg",
            "$host/media/courses/golf-course-6.jpg",
            "$host/media/courses/golf-course-7.jpg",
            "$host/media/courses/golf-course-8.jpg",
            "$host/media/courses/golf-course-9.jpg",
            "$host/media/courses/golf-course-10.jpg",
            "$host/media/courses/golf-course-11.jpg",
            "$host/media/courses/golf-course-12.jpg",
            "$host/media/courses/golf-course-13.jpg",
        ];
    }

    public function addresses() {
        return [
            'Sydney, NSW - AUS',
            'Toronto, ON - CAN',
            'Barcelona, CT - ESP',
            'Tokyo, TYO - JPN',
            'Rome, RM - ITA',
            'Berlin, BE - DEU',
            'Moscow, MOW - RUS',
            'Mumbai, MH - IND',
            'Sao Paulo, SP - BRA',
            'Cape Town, WC - ZAF',
            'Amsterdam, NH - NLD',
            'Zurich, ZH - CHE',
            'Vienna, WI - AUT',
            'Stockholm, ST - SWE',
            'Dublin, D - IRL',
            'Buenos Aires, C - ARG',
            'Cairo, C - EGY',
            'Istanbul, 34 - TUR',
            'Seoul, 11 - KOR',
            'Dubai, DU - ARE',
            'Bangkok, 10 - THA',
            'Helsinki, 18 - FIN',
            'Copenhagen, 84 - DNK',
            'Lisbon, 11 - PRT',
            'Budapest, BU - HUN',
            'Prague, PR - CZE',
            'Athens, A1 - GRC',
            'Warsaw, MZ - POL',
            'Oslo, 03 - NOR',
            'Vienna, 09 - AUT',
            'Brussels, BRU - BEL',
            'Beijing, 11 - CHN',
            'New Delhi, DL - IND',
            'Jakarta, JK - IDN',
            'Manila, 00 - PHL',
            'Kuala Lumpur, KL - MYS',
            'Singapore, 01 - SGP',
            'Mexico City, DIF - MEX',
            'Bogota, DC - COL',
            'Nairobi, 110 - KEN',
            'Johannesburg, GP - ZAF',
            'Wellington, WGN - NZL',
            'Riyadh, 01 - SAU',
            'Doha, DA - QAT',
            'Muscat, MA - OMN',
            'Kuwait City, KU - KWT',
            'Santiago, RM - CHL',
            'Caracas, A - VEN',
            'Lima, LIM - PER',
            'Montevideo, MO - URY',
            'Bucharest, B - ROU',
            'Sofia, 22 - BGR',
            'Belgrade, 00 - SRB',
            'Kyiv, 30 - UKR',
            'Lagos, LA - NGA',
            'Johannesburg, GT - ZAF',
            'Casablanca, 11 - MAR',
            'Auckland, AUK - NZL',
            'Perth, WA - AUS',
            'Vancouver, BC - CAN',
            'San Francisco, CA - USA',
            'Dubai, DU - ARE',
            'Copenhagen, 84 - DNK',
            'Melbourne, VIC - AUS',
            'Cairo, C - EGY',
            'Seoul, 11 - KOR',
            'Kuala Lumpur, KL - MYS',
            'Lisbon, 11 - PRT',
            'Mumbai, MH - IND',
            'Santiago, RM - CHL',
            'Oslo, 03 - NOR',
            'Helsinki, 18 - FIN',
            'Rome, RM - ITA',
            'Warsaw, MZ - POL',
            'Bangkok, 10 - THA',
            'Brussels, BRU - BEL',
            'Madrid, M - ESP',
            'Buenos Aires, C - ARG',
            'Bogota, DC - COL',
            'Prague, PR - CZE',
            'Vienna, 09 - AUT',
            'Istanbul, 34 - TUR',
            'New York, NY - USA',
            'Tokyo, TYO - JPN',
            'Mexico City, DIF - MEX',
            'Paris, IDF - FRA',
            'Moscow, MOW - RUS',
            'Toronto, ON - CAN',
            'Lima, LIM - PER',
            'Beijing, 11 - CHN',
            'Sydney, NSW - AUS',
            'Cape Town, WC - ZAF',
            'Singapore, 01 - SGP',
            'Manila, 00 - PHL',
            'Dubai, DU - ARE',
            'Mumbai, MH - IND',
            'Kuala Lumpur, KL - MYS',
            'Cairo, C - EGY',
            'Rome, RM - ITA',
            'Tokyo, TYO - JPN'
         ];
    }
}
